import {formationView} from './analysis-state.mjs';
import {FORMATIONS,ROLES,playerScore} from './lineup.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const badge=role=>`<span class="role-badge role-${role}">${role}</span>`;
export function renderFormationLayout(team,matchday=team.research?.matchday??'',now=Date.now()){
  const lineup=formationView(team,matchday,now),count=Object.values(lineup.starters).flat().length;
  const restore=!lineup.ai&&team.recommendation?.lineup&&formationView({...team,formation:team.recommendation.lineup.formation},matchday,now).ai;
  const detail=player=>lineup.ai?player.club:playerScore(player)==null?'—':playerScore(player).toFixed(1).replace('.',',');
  return `<div class="formation-layout"><section class="pitch-card"><div class="pitch-card-head"><div><p class="eyebrow">${lineup.ai?'UNDICI DEEPSEEK':'UNDICI SUGGERITO'}</p><h2>${escape(lineup.formation)} <span>· ${count}/11</span></h2></div><span class="demo-tag ${lineup.ai?'ai-lineup-tag':''}">${lineup.ai?'PROPOSTA DEEPSEEK':'BOZZA INDICATIVA'}</span></div>
    ${lineup.reason?`<p class="field-hint pitch-warning">${escape(lineup.reason)}</p>`:''}
    <div class="pitch" aria-label="${lineup.ai?'Formazione suggerita da DeepSeek':'Bozza indicativa della formazione'}">${['A','C','D','P'].map(role=>`<div class="pitch-line">${lineup.starters[role].map(player=>`<div class="pitch-player" data-player-id="${escape(player.id)}"><span class="pitch-player-icon">${role}</span><strong title="${escape(player.name)}">${escape(player.name)}</strong><small>${escape(detail(player))}</small></div>`).join('')}${Array.from({length:lineup.missing[role]},()=>'<div class="pitch-player pitch-empty"><span class="pitch-player-icon">+</span><strong>Da aggiungere</strong></div>').join('')}</div>`).join('')}<div class="pitch-center"></div></div>
    <p class="pitch-caption">${lineup.ai?'Modulo e titolari della proposta DeepSeek salvata. Da verificare prima della consegna.':'Punteggio demo = 55% forma + 45% media voto, solo quando presenti. Senza statistiche i giocatori sono ordinati per nome: questa bozza non usa la proposta DeepSeek. Gli assenti sono esclusi.'}</p>
    ${lineup.ai?`<section class="lineup-bench" aria-label="Panchina suggerita da DeepSeek"><h3>Panchina <span>· ordine di ingresso</span></h3>${lineup.bench.length?`<ol>${lineup.bench.map(player=>`<li data-player-id="${escape(player.id)}">${badge(player.role)}<span><strong>${escape(player.name)}</strong><small>${escape(player.club)}</small></span></li>`).join('')}</ol>`:'<p class="field-hint">Nessuna riserva suggerita.</p>'}</section>`:''}</section>
    <aside class="formation-side"><section class="content-card compact"><p class="eyebrow">SCELTA DEL MODULO</p><h2>Come scendiamo in campo?</h2><label class="select-label" for="formation-select">Modulo</label><select id="formation-select">${Object.keys(FORMATIONS).map(formation=>`<option value="${formation}" ${team.formation===formation?'selected':''}>${formation}</option>`).join('')}</select><p class="field-hint">Una nuova proposta DeepSeek aggiorna automaticamente modulo e campo. Cambiando modulo manualmente vedi una bozza indicativa.</p>${restore?'<button type="button" class="button button-outline" data-action="restore-recommendation">Ripristina proposta DeepSeek</button>':''}</section><section class="content-card compact"><p class="eyebrow">RIEPILOGO</p><h2>${lineup.complete?'Formazione completa':'Mancano giocatori'}</h2><div class="role-summary">${Object.keys(ROLES).map(role=>`<div><span>${badge(role)} ${ROLES[role]}</span><strong>${lineup.starters[role].length}/${FORMATIONS[lineup.formation][role]}</strong></div>`).join('')}</div><button type="button" class="text-button" data-action="go-roster">Vai alla rosa <span>→</span></button></section></aside></div>`;
}
