import {isManualMethod,recommendationLabel} from './recommendation-methods.mjs';
import {formationView} from './analysis-state.mjs';
import {FORMATIONS,ROLES,playerScore,benchByRole} from './lineup.mjs';
import {forecastTotals} from './forecast.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const badge=role=>`<span class="role-badge role-${role}">${role}</span>`;
export function renderFormationLayout(team,matchday=team.research?.matchday??'',now=Date.now(),{saved=false,empty=false,message=''}={}){
  const engine=team.recommendation?.method==='statistical-engine',manual=isManualMethod(team.recommendation?.method),label=manual?recommendationLabel(team.recommendation):'';
  const lineup=empty?{formation:team.formation,starters:Object.fromEntries(Object.keys(ROLES).map(r=>[r,[]])),missing:{...FORMATIONS[team.formation]},bench:[],complete:false,ai:false,reason:message}:formationView(team,matchday,now,{saved}),count=Object.values(lineup.starters).flat().length;
  const restore=!empty&&!lineup.ai&&team.recommendation?.lineup&&formationView({...team,formation:team.recommendation.lineup.formation},matchday,now,{saved}).ai;
  const detail=player=>lineup.ai?player.club:playerScore(player)==null?'—':playerScore(player).toFixed(1).replace('.',',');
  const forecast=lineup.ai?team.recommendation?.forecast:null;
  const totals=forecast?forecastTotals(forecast):null;
  const n=value=>value.toLocaleString('it-IT',{maximumFractionDigits:1});
  const signed=value=>(value>=0?'+':'')+n(value);
  return `<div class="formation-layout"><section class="pitch-card"><div class="pitch-card-head"><div><p class="eyebrow">${lineup.ai?(manual?escape(label):engine?'STATISTICAL ENGINE':'UNDICI AI'):empty?'NESSUNA PROPOSTA':'UNDICI SUGGERITO'}</p><h2>${escape(lineup.formation)} <span>· ${count}/11</span></h2></div><span class="demo-tag ${lineup.ai?'ai-lineup-tag':''}">${lineup.ai?(manual?'SCELTA MANUALE':engine?'STATISTICAL ENGINE':'PROPOSTA AI'):empty?'CAMPO VUOTO':'BOZZA INDICATIVA'}</span></div>
    ${lineup.reason?`<p class="field-hint pitch-warning">${escape(lineup.reason)}</p>`:''}
    ${forecast?`<section class="lineup-forecast" aria-label="Previsione fantapunti"><p class="eyebrow">FANTAPUNTI STIMATI</p><p class="forecast-total"><strong>${n(engine?team.recommendation.engine.expected:totals.expected)}</strong> <span>fp · stima indicativa</span></p><p class="forecast-range">Intervallo plausibile: <strong>${n(forecast.low)}–${n(forecast.high)} fp</strong></p><details><summary>Come nasce la stima</summary><dl class="forecast-breakdown"><div><dt>Voti puri</dt><dd>${n(totals.vote)}</dd></div><div><dt>Bonus</dt><dd>+${n(totals.bonus)}</dd></div><div><dt>Malus</dt><dd>−${n(totals.malus)}</dd></div><div><dt>Modificatori di squadra</dt><dd>${signed(totals.modifier)}</dd></div></dl><p>${escape(forecast.modifierReason)}</p><p>${escape(forecast.assumptions)}</p></details><p class="field-hint">${engine?'Simulazione Statistical engine':'Previsione AI'}, non un punteggio garantito. L’intervallo indica scenari plausibili, senza una probabilità statistica calibrata.</p></section>`:lineup.ai&&!manual?'<p class="field-hint pitch-warning">Genera una nuova proposta per aggiungere la stima fantapunti e i motivi individuali.</p>':''}
    <div class="pitch" aria-label="${empty?'Campo senza formazione salvata':lineup.ai?'Formazione suggerita':'Bozza indicativa della formazione'}">${['A','C','D','P'].map(role=>`<div class="pitch-line">${lineup.starters[role].map(player=>`<button type="button" class="pitch-player" data-action="player-details" data-origin="pitch" data-id="${escape(player.id)}" data-player-id="${escape(player.id)}" aria-label="Statistiche e motivo della scelta: ${escape(player.name)}"><span class="pitch-player-icon">${role}</span><strong title="${escape(player.name)}">${escape(player.name)}</strong><small>${escape(detail(player))}</small></button>`).join('')}${Array.from({length:lineup.missing[role]},()=>`<div class="pitch-player pitch-empty"><span class="pitch-player-icon">+</span><strong>${empty?'—':'Da aggiungere'}</strong></div>`).join('')}</div>`).join('')}<div class="pitch-center"></div></div>
    <p class="pitch-caption">${empty?'Seleziona un metodo con una formazione salvata o genera una nuova proposta.':lineup.ai&&manual?'Modulo e titolari della formazione salvata manualmente.':lineup.ai?'Modulo e titolari della proposta salvata. Tocca un giocatore per statistiche e motivo della scelta. Da verificare prima della consegna.':'Punteggio demo = 55% forma + 45% media voto, solo quando presenti. Senza statistiche i giocatori sono ordinati per nome: questa bozza non usa la proposta. Tocca un giocatore per le statistiche. Gli assenti sono esclusi.'}</p>
    ${lineup.ai?`<section class="lineup-bench" aria-label="Panchina suggerita"><h3>Panchina <span>· priorità per ruolo</span></h3>${lineup.bench.length?`<ol style="--bench-rows:${Math.ceil(lineup.bench.length/2)}">${benchByRole(lineup.bench).map(player=>`<li data-player-id="${escape(player.id)}">${badge(player.role)}<span><strong>${escape(player.name)}</strong><small>${escape(player.club)}</small></span></li>`).join('')}</ol>`:'<p class="field-hint">Nessuna riserva suggerita.</p>'}</section>`:''}</section>
    <aside class="formation-side"><section class="content-card compact"><p class="eyebrow">SCELTA DEL MODULO</p><h2>Come scendiamo in campo?</h2><label class="select-label" for="formation-select">Modulo</label><select id="formation-select">${Object.keys(FORMATIONS).map(formation=>`<option value="${formation}" ${team.formation===formation?'selected':''}>${formation}</option>`).join('')}</select><p class="field-hint">Una nuova proposta aggiorna automaticamente modulo e campo. Cambiando modulo manualmente vedi una bozza indicativa.</p>${restore?'<button type="button" class="button button-outline" data-action="restore-recommendation">Ripristina proposta</button>':''}</section><section class="content-card compact"><p class="eyebrow">RIEPILOGO</p><h2>${empty?'Nessuna formazione salvata':lineup.complete?'Formazione completa':'Mancano giocatori'}</h2><div class="role-summary">${Object.keys(ROLES).map(role=>`<div><span>${badge(role)} ${ROLES[role]}</span><strong>${lineup.starters[role].length}/${FORMATIONS[lineup.formation][role]}</strong></div>`).join('')}</div><button type="button" class="text-button" data-action="go-roster">Vai alla rosa <span>→</span></button></section></aside></div>`;
}
